spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  application:
    name: NETKIM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/netkim
    username: ssafy
    password: ssafy

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  jwt:
    secret: i5E1_POSE_MATE_WITH_JETSON_BOARD

  kopis:
    key: 22e30f62334d4c7bb69c06e13d465711